### PR TITLE
Automatically attempt to generate snippets

### PR DESCRIPTION
**Pull request by anthmatic**
This PR is a WIP and will actually get replaced by a future PR from https://github.com/anthmatic/hubspot-cms-vscode/pulls

In order to keep snippets as up-to-date as possible, this PR introduces a GitHub action that runs every weekday morning and runs the `generate.js` script. If there are any changes, it will:
- checkout a new branch
- commit all of the changes
- push the branch up
- create a PR and add reviewers

A couple of open questions:
- Should this run every day? Or maybe weekly?
- If a PR isn't merged in the same day, should we overwrite the branch/PR on the next day with a fresh set of changes?
- Is there any info that we should add to the PR title or description?

### CODE REVIEW

**Comment by TanyaScales** [comment]
> A couple of open questions:
> 
> * Should this run every day? Or maybe weekly?

I think weekly is sufficient to start -- we can readdress timing after looking at the cadence of PRs and maybe go to even bi-weekly if we are noticing that there aren't many changes being PR'd frequently.


> * If a PR isn't merged in the same day, should we overwrite the branch/PR on the next day with a fresh set of changes?

Yes, I would say to stay in sync as best as possible, if for some reason there is a stale PR up still then we should overwrite/update with the new job

> * Is there any info

You didn't finish this one out -- 😄 -- so will wait to see if you remember what this was going to be

**Review by TanyaScales — APPROVED** [review]

**Comment by anthmatic** [comment]
> You didn't finish this one out

**Comment by TanyaScales** [comment]
> "Is there any info that we should add to the PR title or description?"

Maybe adding something in the description like: "This PR is autogenerated via GitHub Actions and should be reviewed before merging changes"

"Update Snippets" for the title seems fine for now -- we could call out it's automation via something like `[Automatic] Update to Snippets`

but the above is just me spitballing some ideas for additions there

**Comment by anthmatic** [comment]
👍 Thanks, I went with those updates

Closing this PR in favor of: https://github.com/HubSpot/hubspot-cms-vscode/pull/142

**Pull request closed without merging**
